### PR TITLE
Event emitter

### PR DESCRIPTION
**Pull request by bad6e**
@rrgayhart - the beginning of something amazing.

### CODE REVIEW

**Comment by bad6e** [comment]
@rrgayhart  - merging PR - it became a little larger than I would have liked - but event emitters are all working. Thanks for your help!

**Comment by rrgayhart** [comment]
Heya Bret! Awesome work on tackling something more difficult with this!

Part of the assignment was using the PR template to explain the work that you did in the body of the PR: https://gist.github.com/rrgayhart/c64f0966a36a9c47b227

I think this would have been especially important with this kind of PR. You're making broad, sweeping changes and in order to review things, a reviewer needs the context of why you made the decision and what all it's touching. 

If you want to go 'back in time' and update this PR with that information and tag either your 'refactor buddy' or another classmate to review the PR, I'll up the grade but otherwise it'll be 15 of 25 points. Totally up to you!

**Comment by bad6e** [comment]
@jphoenix86
@rrgayhart 

**Current Problem:**

Whenever a ball strikes the side, the paddle, a brick, or the top it emits the Ball class calls the Sound class and emits a sound. Here is how my code looked previously: 

 if (this.ballHitsBrick(i)) {
   Sounds.brick();
 }

The problem here is that the ball knows too much. The ball is calling the a new instance of the sound class resulting in a murky distinction between the two classes.

**The Solution:**

The solution to this problem was use event emitters (WHICH ARE AWESOME BY THE WAY). Instead of having the ball class call a new instance of sound - the ball emits an event. 

Here is the new code: 

if(this.ballHitsBrick(i)) {
  this.emit('brickCollision');
}

Also at the top of my Ball class where I instantiate a new ball I also added the following code:

this.listener = new Listener();
EventEmitter.call(this);
this.on('brickCollision', this.listener.brickCollision);

Now whenever a balls hits a brick - the ball **first** emits an event signaling that the 'brick collision' event has occurred - the event **then** triggers the Listener class; thus removing the responsibility of the ball class to actually call the sound class.

Now this new class - 'Listener' - whose sole duty is to listen for events calls the appropriate sound events when necessary. 

function Listener() {

this.brickCollision = function(){
  Sounds.brick();
  },
}

module.exports = Listener;

*\* Other Refactors **

You will notice that I also added got rid of the start.js class and moved the logic into index.js. There was a lot of code duplication in start.js Yes I should have made another branch for this. 

Also I spelt 'balss' wrong in my commit message. Please excuse typos. 

I also added Game.prototype for every function on the Game class(probably should have done another pr for this too) - But I do believe ( my memory is a bit fuzzy) this was necessary for the event emitters to work.

**Comment by bad6e** [comment]
Thanks @rrgayhart for your feedback!

**Pull request merged**
